### ISSUE TITLE
iOS 10 Compatibility when built with XCode 8

### ISSUE THREAD

**Issue by laud** [OceanLabs/iOS-Print-SDK#257] opened 2016-08-10 17:29 UTC
AddressBook framework was deprecated in iOS 9. When trying to run an app with Print SDK, the app crashes because lack of AddressBook symbols.  This exception appears only an app is built on iOS 10, but running on a iOS 9 or less device.

```
dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /private/var/mobile/Containers/Bundle/Application/9DF8A863-D1A4-4AED-A7A5-3BD112CA8795/MyApp.app/Frameworks/Kite_Print_SDK.framework/Kite_Print_SDK
  Expected in: /System/Library/Frameworks/PassKit.framework/PassKit
 in /private/var/mobile/Containers/Bundle/Application/9DF8A863-D1A4-4AED-A7A5-3BD112CA8795/MyApp.app/Frameworks/Kite_Print_SDK.framework/Kite_Print_SDK
```

I recommend migrating to Contacts framework and/or have preprocessor macros that don't include the AddressBook framework code when built on iOS 10.

**Comment by famanson** [comment] 2016-08-31 09:24
I second this, iOS 10 public launch is imminent, and since we want to implement the new features, we'd need to sacrifice the print SDK :(

**Comment by kkarayannis** [comment] 2016-09-02 13:45
Is this still an issue in the latest Xcode beta? I have been build the SDK for iOS 10 periodically and haven't run into this issue. Since I develop using the demo project, I thought there might be an issue with Cocoapods and/or using Swift but I just tested it and it seems fine.

**Comment by famanson** [comment] 2016-09-04 17:11
@kkarayannis yes I still have this problem. As @laud said above, the issue is not with iOS 10, but when you run the code compiled by XCode 8 on to an iOS 9 device it crashes with this error:

```
dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /private/var/containers/Bundle/Application/1ED5CB2D-CE95-411B-A907-C7B381C798FF/EsplorioDebug.app/Frameworks/Kite_Print_SDK.framework/Kite_Print_SDK
  Expected in: /System/Library/Frameworks/PassKit.framework/PassKit
 in /private/var/containers/Bundle/Application/1ED5CB2D-CE95-411B-A907-C7B381C798FF/EsplorioDebug.app/Frameworks/Kite_Print_SDK.framework/Kite_Print_SDK
```

**Comment by famanson** [comment] 2016-09-06 09:20
is there any updates on this?

**Comment by kkarayannis** [comment] 2016-09-06 10:35
OK, I was able to reproduce this. As you said @famanson, it only happens at runtime on an iOS 9 device, and it only happens when building with frameworks.
I will migrate to the new Contacts framework over the next few days, though iOS 8 will keep using the old code because Contacts was introduced with 9. I don't have an iOS 8 device to test though, so the issue might persist there (although if it does I'm not sure what can be done).
Until I make the changes you can disable Apple Pay by removing the subspec:
```#pod 'Kite-Print-SDK/ApplePay'```

**Comment by famanson** [comment] 2016-09-07 08:24
@kkarayannis cool, thanks

**Comment by kkarayannis** [comment] 2016-09-11 20:45
OK this issue is now fixed in the latest version, 5.4.0

**Closed by kkarayannis** 2016-09-11 20:45 UTC

**Comment by famanson** [comment] 2016-09-12 09:13
@kkarayannis thanks, gonna give this one a go

**Comment by DsrMedia** [comment] 2016-11-02 10:55
@kkarayannis Hi, we have the same issue with our SDK. Could you please share how you fixed it? Right now the workaround seems to be removing and readding the Addressbook and PassKit frameworks.

**Comment by kkarayannis** [comment] 2016-11-02 12:01
Unfortunately I didn't find a solution that would work with Addressbook, so I replaced all the functionality with the new Contacts framework. We only used it to read the shipping address when a user paid with Apple Pay so it wasn't a lot of work. The downside of this approach is that we no longer offer Apple Pay to iOS 8 users, since Contacts was introduced in iOS 9.

**Comment by DsrMedia** [comment] 2016-11-02 12:16
@kkarayannis thanks for the quick reply. We're also only using it to save a contact, so it's not a big deal to switch over to the Contacts framework. We'll consider dropping iOS 8 support. Thanks!

**Comment by deokarDattatray** [comment] 2017-04-18 08:06
Hi is there any update on this issue. i am using PaySafe SDK which internally uses AddressBook. i am not able run application below iOS 10.

**Comment by kkarayannis** [comment] 2017-04-18 08:09
We do not have PaySafe as a dependency in our SDK. This issue has been fixed in our SDK for a while now.

**Comment by deokarDattatray** [comment] 2017-04-18 13:46
What you did to fix this issue. have you replaced Addressbook implementation with Contacts framework?

**Comment by kkarayannis** [comment] 2017-04-18 13:49
Yeah exactly, there can be no reference of Addressbook constants at compile time when targeting iOS 8 or earlier and using PassKit, or it crashes on launch. iOS 9+ should be safe.

**Comment by deokarDattatray** [comment] 2017-04-18 14:00
Thanks for quick reply & co-operation.
