### ISSUE TITLE
Installing without cocoapods

### ISSUE THREAD

**Issue by manujbahl** [OceanLabs/iOS-Print-SDK#53] opened 2015-03-27 22:41 UTC
What do i need to do if i dont use pods. Which gits does the sdk depend on? Howcan i run the sampls without pods

**Comment by dbotha** [comment] 2015-03-27 22:46
Hi Manujbahl,

Any specific reason you can't use CocoaPods? You can see the Sample Apps dependencies here:

    pod 'SDWebImage'
    pod 'AFNetworking', '~> 2.5.0'
    pod 'SVProgressHUD'
    pod 'PayPal-iOS-SDK', '~> 2.4.2'
    pod 'UICKeyChainStore', '~> 2.0.4'
    pod 'LXReorderableCollectionViewFlowLayout'
    pod 'CTAssetsPickerController'
    pod 'InstagramImagePicker'
    pod 'FacebookImagePicker'

I'll take a look at the steps required to build the project without CocoaPods but I suspect in its current form it might be a bit involved.

**Comment by manujbahl** [comment] 2015-03-28 02:24
Thanks 

I installed cocoapods to get past .. but when i build the workspace i get this error
/* com.apple.actool.errors */
: error: Failed to read file attributes for "/Users/MBahl/iOS-Print-SDK/Kite SDK/PSPrintSDK/Images.xcassets /Users/MBahl/iOS-Print-SDK/Kite SDK/PSPrintSDK/KitePrintSDK.xcassets"
    Failure Reason: No such file or directory
/* com.apple.actool.notices */
: warning: Failed to read file attributes for "/Users/MBahl/iOS-Print-SDK/Kite SDK/PSPrintSDK/Images.xcassets /Users/MBahl/iOS-Print-SDK/Kite SDK/PSPrintSDK/KitePrintSDK.xcassets"
    Failure Reason: No such file or directory

DO you know if I am missing something ?

**Comment by manujbahl** [comment] 2015-03-28 02:33
Also when i setup pods on my own app and add the sdk
I get this error

…../PSPrintSDK/OLPaymentViewController.m:35:1: Use of '@import' when modules are disabled

DO you know what is the issue here ?

Manuj

**Comment by manujbahl** [comment] 2015-03-28 03:18
I fixed that in the build settings but when i build it the sdks does not build …
I get the following linker errors
ndefined symbols for architecture i386:
  "_OBJC_CLASS_$_AFHTTPRequestOperation", referenced from:
      objc-class-ref in OLAssetUploadRequest.o
  "_OBJC_CLASS_$_AFHTTPRequestOperationManager", referenced from:
      objc-class-ref in OLJudoPayCard.o
      objc-class-ref in OLPayPalCard.o
  "_OBJC_CLASS_$_AFHTTPSessionManager", referenced from:
      objc-class-ref in OLAnalytics.o
  "_OBJC_CLASS_$_AFJSONRequestSerializer", referenced from:
      objc-class-ref in OLJudoPayCard.o
      objc-class-ref in OLPayPalCard.o
  "_OBJC_CLASS_$_CTAssetsPickerController", referenced from:
      objc-class-ref in OLPhotoSelectionViewController.o
      objc-class-ref in OLOrderReviewViewController.o
      objc-class-ref in OLSingleImageProductReviewViewController.o
  "_OBJC_CLASS_$_SDWebImageManager", referenced from:
      objc-class-ref in OLPrintPhoto.o
      objc-class-ref in OLFrameOrderReviewViewController.o
      objc-class-ref in OLURLDataSource.o
      objc-class-ref in OLSingleImageProductReviewViewController.o
      objc-class-ref in OLPosterViewController.o
  "_OBJC_CLASS_$_SVProgressHUD", referenced from:
      objc-class-ref in OLReceiptViewController.o
      objc-class-ref in OLAddressLookupViewController.o
      objc-class-ref in OLPaymentViewController.o
      objc-class-ref in OLCreditCardCaptureViewController.o
  "_OBJC_CLASS_$_UICKeyChainStore", referenced from:
      objc-class-ref in OLJudoPayCard.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)


These are the steps I took.
1. Set up pods on my existing project
2. Copied  the pod file from the PrintSDK .. added platform :ios, ‘7.0’ to it.
3. pod install
4. clean and build project 


Am i missing something ?

**Comment by dbotha** [comment] 2015-03-28 12:28
Hi Manuj,

Can you share what your CocoaPods Podfile looks like with me?

If you have CocoPods installed you can try out the SDK by running this command in the terminal:

    pod try Kite-Print-SDK

Running the command will download the latest version of the SDK, resolve dependencies and then run the sample app for you.

Thanks,

Deon

**Comment by manujbahl** [comment] 2015-03-28 12:39
I was anle to finally get it going ... 

Thanks
Manuj

**Comment by dbotha** [comment] 2015-03-28 13:45
Fantastic @manujbahl -- let me know if you need any further help :) I'm going to close this issue for now.

**Closed by dbotha** 2015-03-28 13:45 UTC

**Comment by manujbahl** [comment] 2015-03-30 16:57
Deon,

While I have been successful at building the sdk within my project I still can’t get the sample app to build and run.
I am trying the pod try method you listed below and this is the errors i get 

/* com.apple.actool.errors */


: error: Failed to read file attributes for "/private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/Pods/CTAssetsPickerController/Resources/CTAssetsPicker.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/Pods/FacebookImagePicker/FacebookImagePicker.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/Pods/InstagramImagePicker/InstagramImagePicker/InstagramImagePicker.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/PSPrintSDK/Images.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/PSPrintSDK/KitePrintSDK.xcassets"


    Failure Reason: No such file or directory


/* com.apple.actool.notices */


: warning: Failed to read file attributes for "/private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/Pods/CTAssetsPickerController/Resources/CTAssetsPicker.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/Pods/FacebookImagePicker/FacebookImagePicker.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/Pods/InstagramImagePicker/InstagramImagePicker/InstagramImagePicker.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/PSPrintSDK/Images.xcassets /private/tmp/CocoaPods/Try/Kite-Print-SDK/Kite SDK/PSPrintSDK/KitePrintSDK.xcassets"


    Failure Reason: No such file or directory


/* com.apple.actool.document.warnings */

**Comment by dbotha** [comment] 2015-03-30 17:00
Hi Manuj, can you show me the Podfile for your own application (I assume it’s this one: http://bloomapp.co/ <http://bloomapp.co/>) so I can try work out the issue?

**Comment by manujbahl** [comment] 2015-03-30 17:10
Deon ..

Can you start a conversation using your private email instead on the github group.

FYI, my own application is working fine …  these errors are in the sample app using  “pod try Kite-Print-SDK" 

Thanks
Manuj

**Comment by dbotha** [comment] 2015-03-30 17:33
Absolutely, drop me an email at deon@kite.ly <mailto:deon@kite.ly> . I’m just getting a friend to install CocoaPods and try the SDK to see if we hit the same issue.

**Comment by dbotha** [comment] 2015-03-30 17:48
Hi Manuj, I was able to reproduce you issue on my friends mac. I’ll fix it and let you know when you can try it again.
